zookeeper:
  build: ./zookeeper
  ports: 
    - "49181:2181"
    - "22"
nimbus:
  build: ./storm-nimbus
  ports:
    - "49773:3773"
    - "49772:3772"
    - "49627:6627"
    - "22"
  links: 
    - zookeeper:zk
supervisor:
  build: ./storm-supervisor
  ports:
    - "8000"
    - "22"
  links: 
    - nimbus:nimbus
    - zookeeper:zk
ui:
  build: ./storm-ui
  ports:
    - "49080:8080"
    - "22"
  links: 
    - nimbus:nimbus
    - zookeeper:zk